Spice/Areas/Admin/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;
using Spice.Models;
using Spice.Utility;
using Spice.ViewModels;

namespace Spice.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Manager)]
    public class MenuController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IHostingEnvironment _he;
        [BindProperty]
        public MenuVM vM { get; set; }
        public MenuController(ApplicationDbContext db, IHostingEnvironment he)
        {
            _db = db;
            _he = he;
            vM = new MenuVM()
            {
                lstCategory = _db.Category,
                Menu = new Models.Menu()
            };
        }

        // get Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            vM.Menu = await _db.Menu.Include(s => s.Category).Include(s=>s.SubCategory).SingleOrDefaultAsync(m => m.Id == id);
            if (vM.Menu == null)
            {
                return NotFound();
            }

            return View(vM);
        }

        //get Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            vM.Menu = await _db.Menu.Include(s => s.Category).Include(s => s.SubCategory).SingleOrDefaultAsync(m => m.Id == id);
            if (vM.Menu == null)
            {
                return NotFound();
            }

            return View(vM);
        }


        //post Delete
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePost(int id)
        {
            string webRootPath = _he.WebRootPath;
            Menu menu = await _db.Menu.FindAsync(id);

            if (menu != null)
            {
                var imagePath = Path.Combine(webRootPath, menu.Img.TrimStart('\\'));

                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
                _db.Menu.Remove(menu);
                await _db.SaveChangesAsync();

            }

            return RedirectToAction(nameof(Index));
        }

        //get edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();
            vM.Menu = await _db.Menu.Include(m => m.Category).Include(m => m.SubCategory).SingleOrDefaultAsync(m=>m.Id==id);
            
            if (vM.Menu == null)
                return NotFound();
            vM.lstSubCategory = await _db.SubCategory.Where(s => s.CategoryId == vM.Menu.CategoryId).ToListAsync();
            return View(vM);
        }

        //Post Create
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id)
        {
            vM.Menu.SubCategoryId = Convert.ToInt32(Request.Form["SubCategoryId"].ToString());
            if (!ModelState.IsValid)
            {
                vM.lstSubCategory = await _db.SubCategory.Where(s => s.CategoryId == vM.Menu.CategoryId).ToListAsync();
                return View(vM);
            }
            //_db.Menu.Add(vM.Menu);
           // await _db.SaveChangesAsync();

            //Working on Image saving
            string WebRootPath = _he.WebRootPath;
            var files = HttpContext.Request.Form.Files;
            var menu = await _db.Menu.FindAsync(vM.Menu.Id);
            if (files.Count > 0)
            {
                //New Image uploaded
                var upload = Path.Combine(WebRootPath, "images");
                var fileExtensionEdit = Path.GetExtension(files[0].FileName);

                //delete original file
                //if (menu.Img != null)
                //{
                    var imaagepath = Path.Combine(WebRootPath, menu.Img.TrimStart('\\'));
                    if (System.IO.File.Exists(imaagepath))
                    {
                        System.IO.File.Delete(imaagepath);
                    }
               // }
                
                //upload the new image
                using (var fs = new FileStream(Path.Combine(upload, vM.Menu.Id + fileExtensionEdit), FileMode.Create))
                {
                    files[0].CopyTo(fs);
                }
                menu.Img = @"\images\" + vM.Menu.Id + fileExtensionEdit;
            }
            menu.Name = vM.Menu.Name;
            menu.Descrption = vM.Menu.Descrption;
            menu.Price = vM.Menu.Price;
            menu.SpicyLevel = vM.Menu.SpicyLevel;
            menu.CategoryId = vM.Menu.CategoryId;
            menu.SubCategoryId = vM.Menu.SubCategoryId;

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        //get Create
        public IActionResult Create()
        {
            return View(vM);
        }

        //Post Create
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePost()
        {
            vM.Menu.SubCategoryId = Convert.ToInt32(Request.Form["SubCategoryId"].ToString());
            if (!ModelState.IsValid)
            {
                return View(vM);
            }
            _db.Menu.Add(vM.Menu);
            await _db.SaveChangesAsync();

            //Working on Image saving
            string WebRootPath = _he.WebRootPath;
            var files = HttpContext.Request.Form.Files;
            var menu = await _db.Menu.FindAsync(vM.Menu.Id);
            if (files.Count > 0)
            {
                //file uploaded
                var upload = Path.Combine(WebRootPath, "images");
                var fileExtension = Path.GetExtension(files[0].FileName);
                using (var fs = new FileStream(Path.Combine(upload, vM.Menu.Id + fileExtension), FileMode.Create))
                {
                    files[0].CopyTo(fs);
                }
                menu.Img = @"\images\" + vM.Menu.Id + fileExtension;
            }
            else
            {
                //no file uploaded
                var upload = Path.Combine(WebRootPath, @"images\"+SD.DEFAULT_IMAGE);
                System.IO.File.Copy(upload, WebRootPath+@"\images\" +vM.Menu.Id+".png");
                menu.Img = @"\images\" + vM.Menu.Id + ".png";
            }

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Index()
        {
            var menu = await _db.Menu.Include(m=>m.Category).Include(m=>m.SubCategory).ToListAsync();
            return View(menu);
        }
    }
}

Spice/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;
using Spice.Utility;

namespace Spice.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Manager)]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;
        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            var claims = (ClaimsIdentity)this.User.Identity;
            var claim = claims.FindFirst(ClaimTypes.NameIdentifier);

            return View(await _db.ApplicationUsers.Where(u=>u.Id!=claim.Value).ToListAsync());
        }


        public async Task<IActionResult> Lock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
                
            var user = await _db.ApplicationUsers.FirstOrDefaultAsync(u => u.Id == id);
            if (user == null)
            {
                return NotFound();
            }
                

            user.LockoutEnd = DateTime.Now.AddYears(1000);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> UnLock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
                
            var user = await _db.ApplicationUsers.FirstOrDefaultAsync(u => u.Id == id);
            if (user == null)
            {
                return NotFound();
            }
                

            user.LockoutEnd = DateTime.Now;
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Spice/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Create" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Spice/Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i> &nbsp;  Create New </a>
</p>

Spice/Views/Shared/_DeleteAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control" asp-route-id="@Model" value="Delete" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Spice/Views/Shared/_DetailsAndBackToListButton.cshtml
@model int



<div class="row">
    <div class="col-6">
        <a asp-action="Edit" asp-route-id="@Model" class="btn btn-info form-control">Edit</a>
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Spice/Views/Shared/_EditAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" asp-route-id="@Model" value="Update" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

Spice/Views/Shared/_IndividualOrderDetails.cshtml
@model Spice.ViewModels.OrderDeatilsVM
@using Spice.Utility
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<form asp-action="OrderPickup" asp-controller="Order" asp-route-orderId="@Model.orders.Id" method="post">
    <div class="container row border ml-1 backgroundWhiteBorder10Padding" style="width:100%">
        <div class="col-lg-8 col-12" style="border-right:1px solid #bbb9b9">
            <br />
            <input type="hidden" asp-for="orders.Id" />

            <div class="form-group row">
                <div class="col-3">
                    <label>Name</label>
                </div>
                <div class="col-9">
                    <input asp-for="orders.PickupName" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="orders.ApplicationUser.Email"></label>
                </div>
                <div class="col-9">
                    <input asp-for="orders.ApplicationUser.Email" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="orders.ApplicationUser.PhoneNumber"></label>
                </div>
                <div class="col-9">
                    <input asp-for="orders.ApplicationUser.PhoneNumber" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="orders.OrderTotal"></label>
                </div>
                <div class="col-9">
                    <input asp-for="orders.OrderTotal" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="orders.OrderDate"></label>
                </div>
                <div class="col-9">
                    <input value="@Model.orders.PicupTime.ToShortDateString() @Model.orders.PicupTime.ToShortTimeString()" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="orders.Comments"></label>
                </div>
                <div class="col-9">
                    <input asp-for="orders.Comments" disabled class="form-control" />
                </div>
            </div>
        </div>



        <div class="col-lg-4 col-12">
            <h4 class="d-flex justify-content-between align-content-center mb-3">
                <span class="text-muted">Order ID: </span>
                <span class="badge badge-secondary badge-pill">@Model.orders.Id</span>
            </h4>
            <ul class="list-group mb-3">
                @foreach (var details in Model.lstOrderDetails)
                {
                    <li class="list-group-item d-flex justify-content-between">
                        <div>
                            <h6 class="my-0">@details.Name</h6>
                            <small class="text-muted">Quantity : @details.Count</small>
                        </div>
                        <span class="text-muted">@(details.Price * details.Count)</span>
                    </li>
                }
                @if (Model.orders.CouponCode != null)
                {
                    <li class="list-group-item d-flex justify-content-between">
                        <div class="text-success">
                            <h6 class="my-0">Promo Code</h6>
                            <small>@Model.orders.CouponCode</small>
                        </div>
                        <span class="text-success">@(Model.orders.OrderTotalOriginal - Model.orders.OrderTotal)</span>
                    </li>
                }
                <li class="list-group-item d-flex justify-content-between bg-light">
                    <span class="text-info"> Total (USD)</span>
                    <strong class="text-info">$@Model.orders.OrderTotal</strong>
                </li>

            </ul>
            @if (Model.orders.Status.Equals(SD.OrderReady) && (User.IsInRole(SD.Manager) || User.IsInRole(SD.FrontDesk)))
            {
                <button type="submit" class="btn btn-success form-control"><i class="far fa-thumbs-up"></i> Confirm Pickup</button>
            }
            else
            {
                <button type="submit" disabled class="btn btn-info form-control">@Model.orders.Status</button>
            }
        </div>

    </div>
</form>

Spice/Views/Shared/_Layout.cshtml
@using Spice.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor hca
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Spice</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/jquery-ui.css"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.css" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="search-background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">
                    <img src="~/images/mild.png" />
                    <img src="~/images/spicy.png" />
                    <img src="~/images/verySpicy.png" />
                    <label class="text-info" style="cursor:pointer">Spice</label>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(SD.Manager))
                        {
                            <li class="nav-item dropdown text-white-50">
                                <a class="nav-link dropdown-toggle" href="#" id"="NavBarDDMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Content Management</a>
                                <div class="dropdown-menu" aria-labelledby="NavBarDDMenuLink">
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Category" asp-area="Admin">Category</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="SubCategory" asp-area="Admin">Sub Category</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Menu" asp-area="Admin">Menu</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Coupon" asp-area="Admin">Coupons</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="User" asp-area="Admin">Users</a>
                                </div>

                            </li>
                        }

                        @if (User.IsInRole(SD.Manager) || User.IsInRole(SD.Customer) || User.IsInRole(SD.FrontDesk) || User.IsInRole(SD.Kitchen))
                        {
                            <li class="nav-item">
                                <a asp-area="Customer" asp-controller="Orders" asp-action="OrderHistory" class="nav-link">
                                    Order History
                                </a>
                            </li>
                        }
                        @if (User.IsInRole(SD.FrontDesk) || User.IsInRole(SD.Kitchen) || User.IsInRole(SD.Manager))
                        {
                            <li class="nav-item dropdown text-white-50">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Order
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                    @if (User.IsInRole(SD.Kitchen) || User.IsInRole(SD.Manager))
                                    {
                                        <a class="dropdown-item" asp-action="ManageOrder" asp-controller="Orders" asp-area="Customer">Manage Order</a>
                                    }
                                    @if (User.IsInRole(SD.FrontDesk) || User.IsInRole(SD.Manager))
                                    {
                                        <a class="dropdown-item" asp-action="OrderPickup" asp-controller="Orders" asp-area="Customer">Order Pickup</a>
                                    }
                                </div>

                            </li>
                        }

                        @if (hca.HttpContext.Session.GetInt32(@SD.CartCountSession) != null)
                        {
                            <li style="color:white">
                                <a href="/Customer/Cart" class="nav-link">
                                    @{
                                        var count = hca.HttpContext.Session.GetInt32(@SD.CartCountSession);
                                    }
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                </a>
                            </li>
                        }
                        else
                        {

                            <li style="color:white">
                                <a href="/Customer/Cart" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                                </a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top pl-3 footer text-white-50" style="background-color:#343a40">
        <div class="container">
            &copy; 2019 - Spice
        </div>
    </footer>

    <environment include="Development">
        <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=af4djgrspr91j250pytk3gqr976ti7n3j6l2uvm0gj5qjqwc"></script>

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/js/jquery-ui.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=af4djgrspr91j250pytk3gqr976ti7n3j6l2uvm0gj5qjqwc"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
        <script src="~/js/jquery-ui.js"></script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Spice/Views/Shared/_OrderStatus.cshtml
@model string
@using Spice.Utility
<div style="width:100%">
    @if (Model == SD.OrderSubmitted)
    {
        <img src="~/images/OrderPlaced.png" width="100%" />
    }
    @if (Model == SD.OrderProcess)
    {
        <img src="~/images/InKitchen.png" width="100%" />
    }
    @if (Model == SD.OrderReady)
    {
        <img src="~/images/ReadyForPickup.png" width="100%" />
    }
    @if (Model == SD.OrderDone)
    {
        <img src="~/images/completed.png" width="100%" />
    }
</div>

Spice/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

Spice/Views/Shared/_TableButtonPartial.cshtml
@model int

<td style="width:150px">
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model">
            <i class="fas fa-edit"></i>
        </a>

        <a class="btn btn-success text-white" asp-action="Details" asp-route-Id="@Model">
            <i class="fas fa-list-alt"></i>
        </a>

        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>

Spice/Views/Shared/_ThumbnailAreaPartial.cshtml
@model IEnumerable<Menu>
@if (Model.Count() > 0)
{
    <div class="col-12 post @Model.FirstOrDefault().Category.Name.Replace(" ",string.Empty) menuRestaurant">
        <div class="row">
            <h3 class="text-success">@Model.FirstOrDefault().Category.Name</h3>
        </div>
        @foreach (var i in Model)
        {
            <div class="border border-info rounded col-12" style="margin-bottom:10px; margin-top:10px; padding:10px;">
                <div class="row">
                    <div class="col-md-3 col-sm-12">
                        <img src="@i.Img" width="99%" style="border-radius:5px; border:1px solid #bbb9b9" />
                    </div>
                    <div class="col-md-9 col-sm-12">
                        <div class="row pr-3">
                            <div class="col-8">
                                <label class="text-primary" style="font-size:21px;color:maroon;">@i.Name</label>
                                @if (i.SpicyLevel == "1")
                                {
                                    <img srcset="/images/mild.png" title="Mild" />
                                }
                                @if (i.SpicyLevel == "2")
                                {
                                    <img srcset="/images/spicy.png" title="Spicy" />
                                }
                                @if (i.SpicyLevel == "3")
                                {
                                    <img srcset="/images/verySpicy.png" title="Very Spicy" />
                                }
                            </div>
                            <div class="col-4 text-right" style="color:maroon;">
                                <h4>$@i.Price</h4>
                            </div>
                        </div>

                        <div class="row col-12 text-justify d-none d-md-block">
                            <p>@Html.Raw(i.Descrption)</p>
                        </div>
                        <div class="col-md-3 col-sm-12 offset-md-9 text-center">
                            <a asp-action="Details" class="btn btn-success form-control" asp-route-id="@i.Id">Details</a>
                        </div>
                    </div>

                </div>
            </div>
        }
        <div class="p-4">

        </div>
    </div>
}